In [1]:
import pandas as pd
import os
import datetime
import time

In [2]:
pross = os.listdir(r"F:\Qualidade_Florestal\02- MATO GROSSO DO SUL\08- Planejamento e Controle 2°nível\01 - Programação de Sobrevivência\Histórico")
envio = os.listdir(r"F:\Qualidade_Florestal\02- MATO GROSSO DO SUL\08- Planejamento e Controle 2°nível\01 - Programação de Sobrevivência")

In [7]:
df = pd.DataFrame()

for arquivo in pross:
    if "processamento" in arquivo.lower() and not "~" in arquivo:
        tabela = pd.read_excel(f"F:\Qualidade_Florestal/02- MATO GROSSO DO SUL/08- Planejamento e Controle 2°nível/01 - Programação de Sobrevivência/Histórico/{arquivo}")
        tabela ["ID TALHAO"].astype(str)
        tabela ["ID FAZENDA"].astype(str)
        df = df.append(tabela)

In [8]:
directory = r"F:\Qualidade_Florestal\02- MATO GROSSO DO SUL\08- Planejamento e Controle 2°nível\01 - Programação de Sobrevivência"

df1 = pd.DataFrame()

for root, dirs, files in os.walk(directory):
    for file in files:
        if "envio" in file.lower():
            file_path = os.path.join(root, file)
            envio = pd.read_excel(file_path)
            envio["Nome da Origem"] = file
            envio["ID TALHAO"] = envio["ID TALHAO"].astype(str)
            envio["ID FAZENDA"] = envio["ID FAZENDA"].astype(str)
            df1 = pd.concat([df1, envio])

In [9]:
tt = pd.concat([df1, df])

In [11]:
tt.to_excel(r"F:\Qualidade_Florestal\02- MATO GROSSO DO SUL\08- Planejamento e Controle 2°nível\01 - Programação de Sobrevivência\Histórico\Programações sobrevivência.xlsx")

In [13]:
display(tt)

,FONTE,ID AVALIAÇÃO,AVALIAÇÃO,ID FAZENDA,FAZENDA,MUNICÍPIO,ID TALHAO,ÁREA (ha),CLONE,ESPAÇAMENTO,...,Demanda,Sugestão de Demanda,Janela,Parcela,Unnamed: 29,2023-04-18 00:00:00,Descrição do Uso do talhão,Parcela Inventário,Unnamed: 30,Coluna1
0,Cadastro 27.02.xlsx,BATTISTUZI-007-90 DIAS,90 dias,2262,BATTISTUZI,Água Clara,7,38.30,IPB1,"3,60 X 2,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cadastro 27.02.xlsx,DOIS IRMÃOS II-002-30 DIAS,30 dias,2225,DOIS IRMÃOS II,Inocência,2,78.54,AEC0144,"3,55 X 2,65",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cadastro 27.02.xlsx,DOIS IRMÃOS II-008-90 DIAS,90 dias,2225,DOIS IRMÃOS II,Inocência,8,75.47,SUZA0217,"3,55 X 2,65",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cadastro 27.02.xlsx,DOIS IRMÃOS II-009-90 DIAS,90 dias,2225,DOIS IRMÃOS II,Inocência,9,83.03,CO1572,"3,55 X 2,65",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cadastro 27.02.xlsx,DOIS IRMÃOS II-012-30 DIAS,30 dias,2225,DOIS IRMÃOS II,Inocência,12,104.94,IPB2,"3,55 X 2,65",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5781,NaN,TAPERA QUEIMADA-027-90 DIAS,90 DIAS,19,TAPERA QUEIMADA,Borebi,27,56.85,CO0520,"3,80 X 2,10",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5782,NaN,SÃO BENTO-003-90 DIAS,90 DIAS,124,SÃO BENTO,Bauru,3,20.43,SUZA0217,"3,80 X 2,10",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5783,NaN,SÃO BENTO-008-90 DIAS,90 DIAS,124,SÃO BENTO,Bauru,8,21.33,LW11,"3,80 X 2,10",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5784,NaN,KRIKA-001-30 DIAS,30 DIAS,151,KRIKA,Avaí,1,38.68,IPB2,"3,80 X 2,10",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5785,NaN,KRIKA-010-30 DIAS,30 DIAS,151,KRIKA,Avaí,10,4.50,IPB2,"3,80 X 2,10",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN